version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "STACK-TEST-DEPLOY"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mksqpc3q3t0q"
s3_prefix = "STACK-TEST-DEPLOY"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
