AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  local API's

  
Resources:
  AwsWafGstaticIpSet:
    # This API will Sync GStatic IP's to AWS WAF IP Set List
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: awsWafIpSet/ # format is projectPath/
      Handler: lambda.lambdaHandler # format is filename.functionName
      Runtime: python3.9
      Timeout: 30
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /dev
            Method: put
    Metadata:
      BuildMethod: makefile
